Rename openat2() to syscall_openat2().
In glibc v2.43, the openat2() function is defined in system headers
(glibc commit 0f0a5cd3389 "linux: Add openat2 (BZ 31664)"). This cause
compilation errors:

```
$ make
cc -std=c99 -Wall -Wextra -D_GNU_SOURCE -MMD -I ./third_party/k/k/include  -c -o syscalls.o syscalls.c
syscalls.c:89:13: error: conflicting types for ‘openat2’; have ‘long int(int,  const char *, struct open_how *, size_t)’ {aka ‘long int(int,  const char *, struct open_how *, long unsigned int)’}
   89 | static long openat2(int dirfd, const char *path, struct open_how *how,
      |             ^~~~~~~
In file included from /usr/include/bits/fcntl.h:61,
                 from /usr/include/fcntl.h:35,
                 from syscalls.c:19:
/usr/include/bits/fcntl-linux.h:484:12: note: previous declaration of ‘openat2’ with type ‘int(int,  const char *, const struct open_how *, long unsigned int)’
  484 | extern int openat2 (int __dfd, const char * __filename,
      |            ^~~~~~~
make: *** [<builtin>: syscalls.o] Error 1
```

Renaming the function allows us to build with the latest glibc.